# Tailored Dependabot configuration for your project
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 4
    
    groups:
      # React ecosystem updates
      react-ecosystem:
        patterns:
          - "react"
          - "react-dom"
          - "react-select"
          - "@headlessui/react"
          - "@vitejs/plugin-react"
          - "eslint-plugin-react*"
        
      # Database and backend utilities
      backend-stack:
        patterns:
          - "mongodb"
          - "mongoose"
          - "bcryptjs"
          - "body-parser"
          - "cors"
          - "rate-limiter-flexible"
        
      # Security and validation packages
      security-validation:
        patterns:
          - "xss"
          - "obscenity"
          - "@allemandi/bible-validate"
        
      # Development tooling (ESLint, build tools)
      dev-tooling:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "vite"
          - "netlify-cli"
        dependency-type: "development"
        
      # Styling and UI framework
      styling-ui:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "postcss"
          - "clsx"
        
      # Utilities and icons
      utilities:
        patterns:
          - "lucide-react"
          - "simple-icons"
          - "papaparse"
          - "uuid"
          - "dotenv"
          - "globals"
    
    # Ignore major version updates for critical packages
    ignore:
      # Keep React stable - only allow minor/patch updates
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      # MongoDB/Mongoose - major updates can have breaking changes
      - dependency-name: "mongodb"
        update-types: ["version-update:semver-major"]
      - dependency-name: "mongoose"
        update-types: ["version-update:semver-major"]
      # Vite major updates sometimes require config changes
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
    
    # Prioritize security updates
    allow:
      # Always allow security updates
      - dependency-type: "all"
        update-types: ["security"]
      # Allow all dev dependency updates (they're safer)
      - dependency-type: "development"
      # For production, allow minor and patch updates
      - dependency-type: "production"
        update-types: ["minor", "patch"]
    
    # Add labels for PR organization
    labels:
      - "dependencies"
      - "automated"
    
    # Custom commit messages
    commit-message:
      prefix: "deps"
      include: "scope"
