[build]
  command = "yarn build"
  publish = "build"

# If deploying Express backend elsewhere, set up a proxy like below:
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-express-backend-url/api/:splat"
#   status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
