[build]
  command = "yarn build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "vite" # Command to start Vite dev server
  targetPort = 5173 # Port Vite runs on

[functions]
  included_files = ["src/data/bible-counts.json", "src/data/themes.json"]

# Redirect all API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
